-- Using ENUM for levels to restrict input and prevent spelling errors
CREATE TABLE member (
    id INT AUTO_INCREMENT PRIMARY KEY, -- Primary key autogenerated as per rubric
    name VARCHAR(255) NOT NULL,
    details TEXT,
    title VARCHAR(100),
    level ENUM('Bronze', 'Silver', 'Gold') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
-- AWS RDS by default use InnoDb bu for in case safety we are assigning it if we don't use InnoDB
-- then Foreign keys will be ignored, there will be No referential integrity and No cascade delete   

CREATE TABLE event (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    capacity INT NOT NULL,
    level ENUM('Bronze', 'Silver', 'Gold') NOT NULL,
    date DATE NOT NULL,
    UNIQUE(date) -- prevent double-booking or replicates events on the same day
) ENGINE=InnoDB;

-- junction table to manage the Many-to-Many relationship between Members and Events
CREATE TABLE registration (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_id INT NOT NULL,
    member_id INT NOT NULL,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- foreign keys ensure referential integrity
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE,
    CONSTRAINT fk_member FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE,
    -- cascade block you from deleting a member if they were still registered for an event. You would have to manually delete all their registrations first before the database would let you remove the member

    -- member can only register once per event
    CONSTRAINT unique_registration UNIQUE(event_id, member_id)
) ENGINE=InnoDB;

INSERT INTO member (name, details, title, level)
VALUES 
('Ali Raza', 'VIP Member', 'Manager', 'Gold'),
('Muhammad Hadi', 'Regular Member', 'Engineer', 'Silver');

INSERT INTO event (name, capacity, level, date)
VALUES 
('VIP Gala', 100, 'Gold', '2026-05-01'),
('Networking Night', 50, 'Silver', '2026-06-01');